### PR TITLE
fix: restore persistence functionality

### PR DESCRIPTION
**Pull request by tshakalekholoane**
This addresses an issue where the switch to using systemd templates and format specifiers introduced a regression, causing the persistence functionality to no longer work as expected.

To resolve this issue, we have reverted to an earlier implementation
that manually writes all the units and uses Go's `exec.LookPath` to
resolve the shell path.

Resolves: #65

### CODE REVIEW

**Comment by pepa65** [comment]
Perfect! The vast majority should at least have bash installed.

**Comment by tshakalekholoane** [comment]
Thank you again for helping with this, @pepa65! I really appreciate it.

**Comment by pepa65** [comment]
Thank you for saying that. I have an interest in the topic, also to make sure the app I'm using works well, but sometimes I wondered if I should not get mixed up.

**Comment by tshakalekholoane** [comment]
Not at all! Feel free to chime in whenever you have something to say :smile:. I mean maybe our tastes are different in that you may prefer to have more functionality and support a wider set of configurations but I think where it matters your contributions have been invaluable. I have learned a lot from our discussions and going through the modifications you've done on your fork.

**Comment by pepa65** [comment]
I've learned a lot from your go programming with using interfaces. 😄 (Well, I'm still learning..!)

**Comment by tshakalekholoane** [comment]
Is it okay if I add you to the repo, @pepa65?

**Comment by pepa65** [comment]
Sure, fine with me. Would you like me to do stuff??

**Comment by tshakalekholoane** [comment]
Yes, if it's not too much to ask. I mean you are already helping out with issues. There's also been a few times where I've pushed changes to main that and you pointed out something only after the fact so I think it will also help to have a review process to avoid having something like that happening too often.

**Comment by pepa65** [comment]
OK, I will try my best..!

**Pull request merged**
